# Отключаем функции, которых нет на донгле, чтобы избежать ошибок сборки
# Отключаем экраны и подсветку для донгла
CONFIG_ZMK_DISPLAY=n
CONFIG_ZMK_RGB_UNDERGLOW=n

# Принудительно включаем подсистему сенсоров для фантомных энкодеров,
# но отключаем их прерывания, чтобы донгл не пытался их "слушать" физически
CONFIG_SENSOR=y
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=n
